/* Catalogue OSCE Pharmacie — 21 cas regroupés par plainte.
   Chaque cas : { id, plainte, variant, opening, answers:[{q,a}], sections:[{title, items:[label]}] }
   Les ids d'items de grille sont synthétisés à l'exécution (caseId_sectionIndex_itemIndex). */
const CASES = [
  /* ===================== BRÛLURE ===================== */
  {
    id: "brulure-bebe", plainte: "Brûlure", variant: "Bébé (10 mois)",
    opening: "Bonjour, je viens pour une crème anti-brûlure pour ma voisine.",
    answers: [
      { q: "Qui ?", a: "Le bébé de 10 mois de ma voisine (pèse 9 kg)." },
      { q: "Mécanisme ?", a: "La maman tenait le bébé en sortant le plat du four ; le poignet a cogné le plat chaud." },
      { q: "Aspect ?", a: "C'est rouge, pas de cloques, pas de zone blanche ni noire." },
      { q: "Surface ?", a: "Inférieure à une pièce de 2 €." },
      { q: "Depuis ?", a: "C'est arrivé il y a 1 heure." },
      { q: "Actions ?", a: "Main passée sous l'eau froide, environ 5 minutes." },
      { q: "État ?", a: "A un peu pleuré sur le coup, maintenant il va bien." },
      { q: "Médicaments ?", a: "Aucun médicament en cours." },
      { q: "Question", a: "Doit-elle mettre un pansement sur la crème que vous proposez ?" },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Demande qui est le patient (bébé de 10 mois)",
        "Demande le type de brûlure (thermique)",
        "Évalue le degré (1er degré car rouge)",
        "Évalue la surface (<5%) et la localisation",
        "Évalue l'étendue (< 2 €)",
        "Questionne la maltraitance / 1ère fois",
        "Demande depuis quand",
        "Demande les actions entreprises",
        "Demande l'historique médicamenteux",
      ]},
      { title: "Décision", items: [
        "Annonce qu'il peut prendre en charge",
        "Ou réfère vers un médecin si nécessaire",
      ]},
      { title: "Conseils", items: [
        "Bien refroidir la brûlure (règle 15/15/15)",
        "Surtout ne pas mettre de glace",
        "Hygiène des mains pour le traitement",
        "Proposer un hydrogel (ex. Flamigel)",
        "Appliquer jusqu'à disparition de la rougeur",
        "Pansement non obligatoire",
        "Protéger du soleil pendant 1 an",
        "Paracétamol si douleurs",
        "Surveiller l'état général les jours/semaines suivants",
        "Consulter si altération de l'état général",
        "Consulter si mauvaise cicatrisation",
      ]},
    ],
  },
  {
    id: "brulure-adulte", plainte: "Brûlure", variant: "Adulte (BBQ)",
    opening: "Bonjour, je me suis brûlé en allumant le barbecue. Puis-je avoir de la Flammazine ?",
    answers: [
      { q: "Qui ?", a: "Oui c'est pour moi, homme de 50 ans." },
      { q: "Localisation ?", a: "Le bas de la cuisse." },
      { q: "Surface ?", a: "Moins d'une demi-paume de main." },
      { q: "Aspect ?", a: "Rouge avec des cloques, un peu douloureux." },
      { q: "Tétanos ?", a: "Je ne me souviens plus de la date de mon dernier vaccin tétanos." },
      { q: "Depuis ?", a: "C'est arrivé hier soir." },
      { q: "Actions ?", a: "J'ai rapidement passé sous l'eau très froide." },
      { q: "Médicaments ?", a: "Metformine 500, Asaflow, Lisinopril 20, Toujeo, Lorazépam 2,5." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Demande qui est le patient (homme, 50 ans)",
        "Vérifie le statut vaccinal tétanos",
        "Demande de décrire la brûlure",
        "Questionne le risque d'infection",
        "Identifie le type (thermique)",
        "Évalue le degré (2e degré : rouge + cloques)",
        "Évalue la surface (<10%) et la localisation",
        "Évalue l'étendue (< ½ paume)",
        "Demande depuis quand",
        "Demande les actions entreprises",
        "Relève l'historique médicamenteux (présence de metformine)",
      ]},
      { title: "Décision", items: [
        "Peut prendre en charge",
        "Réfère au médecin (statut vaccinal / rappel tétanos)",
      ]},
      { title: "Conseils", items: [
        "Bien refroidir la brûlure (règle 15/15/15)",
        "Surtout ne pas mettre de glace",
        "Hygiène des mains pour le traitement",
        "Proposer un hydrogel (ex. Flamigel)",
        "Flammazine sans intérêt clinique démontré (< hydrogel)",
        "Appliquer jusqu'à disparition de la rougeur",
        "Pansement non obligatoire",
        "Ne pas percer les cloques",
        "Protéger du soleil pendant 1 an",
        "Paracétamol si douleurs",
        "Surveiller l'état général les jours/semaines suivants",
        "Consulter si altération de l'état général",
        "Consulter si mauvaise cicatrisation",
        "Vigilance : diabétique, plus à risque de complications",
      ]},
    ],
  },
  /* ===================== HÉMORROÏDES ===================== */
  {
    id: "hemorroides-1", plainte: "Hémorroïdes", variant: "Cas 1 — chauffeur 53 ans",
    opening: "Bonjour, je pense avoir des hémorroïdes. Pouvez-vous me donner quelque chose ? C'est assez douloureux.",
    answers: [
      { q: "Qui ?", a: "Patient de 53 ans, chauffeur de bus." },
      { q: "Poids ?", a: "Corpulence normale, pas de surpoids." },
      { q: "Symptômes ?", a: "Douleur surtout assis (toute la journée), parfois un peu de sang sur le papier." },
      { q: "Selles ?", a: "Selles peut-être plus foncées, je ne regarde pas trop." },
      { q: "Depuis ?", a: "Environ 10 jours." },
      { q: "Antécédents ?", a: "Déjà eu ça, jamais diagnostiqué chez le médecin." },
      { q: "Actions ?", a: "Rien, je pensais que ça allait passer." },
      { q: "Signes généraux ?", a: "Pas de perte de poids, pas de fatigue, pas de prurit." },
      { q: "Transit ?", a: "J'alterne constipation et diarrhée, plutôt des selles liquides." },
      { q: "Dépistage ?", a: "Jamais de colotest ni de coloscopie." },
      { q: "Boissons ?", a: "Beaucoup de coca, peu d'eau." },
      { q: "Médicaments ?", a: "Du tadalafil de temps en temps." },
      { q: "Demande", a: "En attendant le médecin, je veux bien quelque chose pour soulager." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Demande l'âge",
        "Questionne la perte de poids",
        "Questionne le sport / la sédentarité",
        "Antécédent de cancer colorectal",
        "Pas de maladie inflammatoire intestinale",
        "1ère fois ?",
        "Présence de sang ?",
        "Selles noires ?",
        "Douleur ?",
        "Prurit ?",
        "Transit lent (constipation) ?",
        "Fatigue ?",
        "Habitudes alimentaires / alcool / épices ?",
        "Demande depuis quand",
        "Demande les actions entreprises",
        "1er diagnostic posé par un médecin ?",
        "Demande les autres médicaments",
      ]},
      { title: "Décision", items: [
        "Délivre une crème type vaseline avant consult (Fitoroïd, Cose-protect…)",
        "Propose un colotest",
        "Colotest à faire quand plus de saignement",
        "NE PAS proposer de crème aux corticoïdes (présence de sang)",
        "Renvoi vers le médecin (> 50 ans)",
      ]},
      { title: "Conseils", items: [
        "Appliquer la crème 2 à 3×/jour",
        "Lutter contre la constipation : fibres, laxatifs doux",
        "Bien s'hydrater",
        "Éviter le coca et les aliments irritants",
        "Limiter le temps aux toilettes, éviter les poussées (tabouret)",
        "Douleur : paracétamol 1er choix ou ibuprofène",
        "Veinotoniques peu efficaces",
        "Amélioration attendue sous 7 jours",
      ]},
    ],
  },
  {
    id: "hemorroides-2", plainte: "Hémorroïdes", variant: "Cas 2 — enceinte T3",
    opening: "Bonjour, j'ai des hémorroïdes et je suis enceinte (3e trimestre). Que puis-je prendre pour accélérer la guérison ?",
    answers: [
      { q: "Transit ?", a: "Je suis constipée." },
      { q: "Grossesse ?", a: "3e trimestre." },
      { q: "Sport ?", a: "Je ne fais plus beaucoup de sport." },
      { q: "Sang ?", a: "Pas de sang." },
      { q: "Douleur ?", a: "Surtout quand je vais à selles." },
      { q: "Antécédents ?", a: "J'ai déjà eu ça lors de ma première grossesse." },
      { q: "Demande", a: "Je voudrais aussi des comprimés, pas seulement une crème." },
      { q: "Ibuprofène ?", a: "J'ai de l'ibuprofène à la maison, je peux en prendre pour la douleur ?" },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Questionne la perte de poids",
        "Questionne le sport / la sédentarité",
        "Antécédent de cancer colorectal",
        "Pas de maladie inflammatoire intestinale",
        "1ère fois ?",
        "Présence de sang ?",
        "Selles noires ?",
        "Douleur ?",
        "Prurit ?",
        "Transit lent (constipation) ?",
        "Fatigue ?",
        "Habitudes alimentaires / épices ?",
        "Demande depuis quand",
        "Demande les actions entreprises",
        "1er diagnostic posé par un médecin ?",
        "Demande les autres médicaments",
      ]},
      { title: "Décision", items: [
        "Délivre une crème type vaseline",
        "Délivre une crème corticoïde (pas de sang)",
      ]},
      { title: "Conseils", items: [
        "Appliquer la crème 2 à 3×/jour (si vaseline)",
        "Ou Trianal 3×/j ou Scheriproct 2×/j",
        "Corticoïde : max 1–2 semaines",
        "Lutter contre la constipation : fibres, laxatifs doux",
        "Bien s'hydrater",
        "Éviter le coca et les aliments irritants",
        "Limiter le temps aux toilettes, éviter les poussées (tabouret)",
        "Douleur : paracétamol 1er choix",
        "Surtout pas d'ibuprofène",
        "Veinotoniques peu efficaces",
        "Venoruton possible au 3e trimestre",
        "Amélioration sous 7 jours, sinon médecin",
      ]},
    ],
  },
  /* ===================== YEUX SECS ===================== */
  {
    id: "yeux-secs-1", plainte: "Yeux secs", variant: "Cas 1 — homme 45 ans",
    opening: "Bonjour, j'ai une sensation de saleté dans les yeux depuis quelques jours (homme de 45 ans, sans antécédent). Pas de sécrétion, ni de croûtes, ni de douleur. Pouvez-vous me délivrer un collyre pour désinfecter ?",
    answers: [
      { q: "Allergie ?", a: "Non, pas de rhume ni d'antécédent d'allergie." },
      { q: "Lentilles ?", a: "Non, pas de lentilles de contact." },
      { q: "Écrans ?", a: "Fin du télétravail depuis 1 mois, plus de 5 h/j devant l'ordinateur." },
      { q: "Pathologies ?", a: "Pas de glaucome ni autre pathologie oculaire." },
      { q: "Actions ?", a: "J'ai essayé le sérum physiologique, pas assez efficace." },
      { q: "Médicaments ?", a: "Aucun (parfois du Nustasium pour bien dormir)." },
      { q: "Ophtalmo ?", a: "Pas de consultation ophtalmo." },
      { q: "Fréquence ?", a: "Surtout si air sec et écran, plus fréquent en hiver." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Demande l'âge / le sexe",
        "Porteur de lentilles ?",
        "Travail sur ordinateur ?",
        "Allergie aux pollens ?",
        "Autres pathologies (diabète, maladie auto-immune) ?",
        "Opération récente ?",
        "Symptômes : picotement, larmoiement, rougeur, grain de sable",
        "Rougeur importante ?",
        "Douleur ?",
        "Troubles de la vision ?",
        "Photophobie importante ?",
        "Infection (croûtes/pus) ou vésicules ?",
        "Demande depuis quand",
        "Demande la fréquence (chronique ?)",
        "Demande les actions entreprises",
        "Si chronique : consultation ophtalmo ?",
        "Autres médicaments (anticholinergiques, hormones, rétinoïdes…)",
      ]},
      { title: "Conseils", items: [
        "Collyre en journée (peu importe le choix)",
        "En plus : gel / pommade la nuit",
        "Posologie : 1×/h ou à la demande",
        "Objectif : soulagement immédiat",
        "Administration : se laver les mains",
        "Tirer la paupière inférieure, regarder vers le haut",
        "Instiller 1 goutte (éviter le contact embout/œil)",
        "Garder l'œil fermé + presser le canal lacrymal",
        "Précaution : durée de conservation",
        "Limiter les écrans",
        "Règle des 20-20-20",
        "Bien s'hydrater (min 1,5 L)",
        "Hygiène des paupières si symptômes persistants",
        "Limiter le Nustasium",
        "Médecin si aggravation ou pas d'amélioration",
      ]},
    ],
  },
  {
    id: "yeux-secs-2", plainte: "Yeux secs", variant: "Cas 2 — femme 27 ans",
    opening: "Bonjour, je viens chercher des gouttes pour mes yeux secs (jeune femme de 27 ans).",
    answers: [
      { q: "Qui ?", a: "Oui pour moi, j'ai 27 ans." },
      { q: "Lentilles ?", a: "Oui, lentilles souples mensuelles, habituellement bien supportées." },
      { q: "Écrans ?", a: "Oui, je prépare un rapport de thèse, minimum 8 h/j." },
      { q: "Allergie ?", a: "Non, pas que je sache." },
      { q: "Pathologies ?", a: "Aucune." },
      { q: "Tabac ?", a: "Non." },
      { q: "Symptômes ?", a: "Yeux secs et fatigués (grain de sable), un peu rouges." },
      { q: "Gravité ?", a: "Pas de rougeur importante, pas de douleur, pas de trouble de la vision ni photophobie." },
      { q: "Infection ?", a: "Pas de croûtes ni de pus." },
      { q: "Depuis ?", a: "Depuis ma thèse, environ 2 semaines." },
      { q: "Actions ?", a: "Thealoz Duo 1×/j le matin : ça soulage mais ça ne dure pas." },
      { q: "Médicaments ?", a: "Roaccutane 20 (acné, 1×/j depuis 1 mois), Noranelle 30 (3 ans), Nustasium si insomnie." },
      { q: "Aggravation ?", a: "Peut-être depuis le Roaccutane, comme ma peau plus sèche." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Porteur de lentilles ?",
        "Travail sur ordinateur ?",
        "Allergie aux pollens ?",
        "Autres pathologies (diabète, maladie auto-immune) ?",
        "Opération récente ?",
        "Symptômes : picotement, larmoiement, rougeur, grain de sable",
        "Rougeur importante ?",
        "Douleur ?",
        "Troubles de la vision ?",
        "Photophobie importante ?",
        "Infection (croûtes/pus) / vésicules ?",
        "Demande depuis quand",
        "Demande la fréquence",
        "Actions entreprises + résultat",
        "Autres médicaments (+ fréquence du Nustasium)",
      ]},
      { title: "Conseils", items: [
        "Collyre en journée (Thealoz OK)",
        "En plus : gel / pommade la nuit (plusieurs facteurs de risque)",
        "Sans conservateurs (port de lentilles) — Thealoz OK",
        "Posologie : 1×/h ou à la demande",
        "Objectif : soulagement immédiat",
        "Administration : se laver les mains",
        "Tirer la paupière inférieure, regarder vers le haut",
        "Instiller 1 goutte (éviter le contact embout/œil)",
        "Garder l'œil fermé + presser le canal lacrymal",
        "Précaution : durée de conservation",
        "Éviter les lentilles si possible (surtout sous Roaccutane)",
        "Limiter les écrans",
        "Règle des 20-20-20",
        "Bien s'hydrater (min 1,5 L)",
        "Hygiène des paupières si persistance",
        "Roaccutane : importance de l'hydratation peau et yeux",
        "Pilule : ne pas l'arrêter (prise de Roaccutane)",
        "Éviter le Nustasium",
        "Médecin si aggravation / pas d'amélioration",
        "Aborder la sécheresse oculaire à la prochaine consult dermato",
      ]},
    ],
  },
  /* ===================== RHINITE ALLERGIQUE ===================== */
  {
    id: "rhinite-1", plainte: "Rhinite allergique", variant: "Cas 1 — jardinage",
    opening: "Bonjour, pouvez-vous me donner un anti-allergique à prendre avant d'aller jardiner ? Je voudrais un traitement qui me soulage vite.",
    answers: [
      { q: "Qui ?", a: "Homme de 35 ans, sans antécédent médical connu." },
      { q: "Symptômes ?", a: "À la tonte : éternuements, nez parfois bouché, yeux qui pleurent. Pas de fièvre ni douleur." },
      { q: "Respiration ?", a: "Globalement bonne, un peu difficile ce week-end, mais c'est passé." },
      { q: "Depuis ?", a: "1 semaine, depuis le beau temps et la tonte (+++ ce week-end, yeux rouges et gonflés)." },
      { q: "Récurrence ?", a: "Oui, chaque année plus ou moins à la même période." },
      { q: "Actions ?", a: "Rien, je pensais que ça ne durerait pas." },
      { q: "Médicaments ?", a: "Aucun, du paracétamol de temps en temps." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Yeux qui grattent / qui coulent ?",
        "Nez : chatouille / éternuements / encombrement ?",
        "Gorge : symptômes ?",
        "Signaux d'alarme (fièvre, respiration sifflante…) ?",
        "Demande depuis quand",
        "Récurrence ?",
        "Actions entreprises ?",
        "Autres traitements ?",
      ]},
      { title: "Décision", items: [
        "Prise en charge à l'officine",
      ]},
      { title: "Conseils", items: [
        "Rincer yeux/nez au sérum physiologique",
        "Ne pas laisser pendre le linge dehors",
        "Se laver les cheveux le soir",
        "Aérer < 5-10 min/j",
        "Anti-H1 : cétirizine ou loratadine 1×/j le soir",
        "Ou Allegratab 1×/j",
        "Ou azélastine collyre 1 goutte 2×/j (Livostin/Allergodil)",
        "Ou azélastine spray nasal 1 dose 2×/j",
        "Ou cétirizine per os + anti-H1 collyre/spray en complément",
      ]},
    ],
  },
  {
    id: "rhinite-2", plainte: "Rhinite allergique", variant: "Cas 2 — Gérard, asthme",
    opening: "Bonjour, Gérard vous demande un remède efficace pour son rhume des foins qui recommence. Un traitement qui le couvre pour la saison et le soulage vite.",
    answers: [
      { q: "Symptômes ?", a: "Rhume des foins : yeux qui pleurent, gorge qui gratte, éternuements, nez qui chatouille." },
      { q: "Alarme ?", a: "Pas de température." },
      { q: "Depuis ?", a: "4-5 jours, depuis la tonte. Chaque année, ce n'est pas la première fois." },
      { q: "Actions ?", a: "Rien à la maison. Les autres années : un comprimé, parfois un spray nasal." },
      { q: "Médicaments ?", a: "Inuvair Nexthaler (asthme)." },
      { q: "Asthme ?", a: "Oui j'ai de l'asthme, mais bien contrôlé, pas de traitement de secours récent ni de réveil nocturne." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Asthme : stable ? respiration sifflante ?",
        "Yeux qui grattent / qui coulent ?",
        "Nez : chatouille / éternuements / encombrement ?",
        "Gorge : symptômes ?",
        "Signaux d'alarme (fièvre, respiration sifflante…) ?",
        "Demande depuis quand",
        "Récurrence ?",
        "Actions entreprises ?",
        "Autres traitements (DPP) ?",
      ]},
      { title: "Décision", items: [
        "Prise en charge à l'officine",
      ]},
      { title: "Conseils", items: [
        "Rincer yeux/nez au sérum physiologique",
        "Ne pas laisser pendre le linge dehors",
        "Se laver les cheveux le soir",
        "Aérer < 5-10 min/j",
        "Mométasone (Momepax) : traitement de fond",
        "Agiter le flacon avant emploi",
        "1 à 2 doses/narine, matin ou soir",
        "Pas vers la cloison nasale (éviter irritations/saignements)",
        "Effet non immédiat (min 4 jours), maximal vers J15",
        "En attendant : anti-H1 cétirizine/loratadine 1×/j le soir",
        "Ou Allegratab 1×/j",
        "Ou azélastine collyre 1 goutte 2×/j (Livostin/Allergodil)",
        "Ou azélastine spray nasal 1 dose 2×/j",
        "Ou cétirizine per os + anti-H1 collyre/spray",
      ]},
    ],
  },
  /* ===================== MAL DE GORGE ===================== */
  {
    id: "gorge-1", plainte: "Mal de gorge", variant: "Cas 1 — enceinte T1",
    opening: "Bonjour, j'ai mal à la gorge. Pouvez-vous me donner quelque chose ? C'est assez douloureux.",
    answers: [
      { q: "Qui ?", a: "Patiente de 28 ans (65 kg), maman d'un enfant de 18 mois en crèche." },
      { q: "Grossesse ?", a: "Enceinte, 1er trimestre (10 semaines d'aménorrhée)." },
      { q: "Douleur ?", a: "Assez intense, j'ai vraiment du mal à avaler." },
      { q: "Fièvre ?", a: "37,9 °C, ce n'est pas vraiment de la fièvre, si ?" },
      { q: "Depuis ?", a: "Depuis 2 jours." },
      { q: "Actions ?", a: "Paracétamol 1 g (2 hier, 1 aujourd'hui)." },
      { q: "Strepfen ?", a: "J'ai du Strepfen chez moi, puis-je le prendre ?" },
      { q: "Médicaments ?", a: "Aucun, sauf vitamines de grossesse et paracétamol." },
      { q: "Questions", a: "Pourquoi aller chez le médecin ? C'est quoi le CMV ?" },
      { q: "Relance", a: "En fait je ne vous l'ai pas dit, mais je suis enceinte." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Pose la question de la grossesse",
        "Stade de la grossesse (T1)",
        "Douleur ?",
        "Fièvre ?",
        "Demande depuis quand",
        "Actions entreprises (paracétamol pris)",
        "Autres traitements (Strepfen) ?",
      ]},
      { title: "Décision", items: [
        "Réfère au médecin (risque CMV)",
        "Prise en charge symptomatique à l'officine en attendant",
      ]},
      { title: "Conseils", items: [
        "Hydratation",
        "Boissons chaudes",
        "Miel / citron / sucer des bonbons",
        "Paracétamol 1 g/prise, jusqu'à 3×/j (4-6 h entre les prises)",
        "Spray gorge : Medica spray (ou Néo-golaseptine) 3-5 pulv. 3×/j",
        "Ou comprimés : Medica (ou Golaseptine lidocaïne)",
        "Déconseillés chez la femme enceinte : Collutabs, Strepsils, Thymospray, Colludol",
        "Risque CMV : malformations (surdité, troubles neurologiques)",
        "Rappeler que tous les AINS sont contre-indiqués (Strepfen)",
      ]},
    ],
  },
  {
    id: "gorge-2", plainte: "Mal de gorge", variant: "Cas 2 — femme 45 ans, asthme",
    opening: "Bonjour, j'ai mal à la gorge depuis 2 jours. Je n'ai plus rien dans ma pharmacie. Femme de 45 ans.",
    answers: [
      { q: "Grossesse ?", a: "Pas enceinte." },
      { q: "Fièvre ?", a: "Un peu de fièvre 38,5 °C depuis cet après-midi, non persistante." },
      { q: "Éruption ?", a: "Pas d'éruption cutanée." },
      { q: "Toux ?", a: "Pas de toux." },
      { q: "Douleur ?", a: "En avalant des deux côtés, je mange encore. Impression d'avaler des barbelés." },
      { q: "Fatigue ?", a: "Oui forcément, mais je ne me ménage pas." },
      { q: "Depuis ?", a: "Depuis 2 jours, c'est la première fois." },
      { q: "Actions ?", a: "Pastilles Medica menthe et une Sédergine de la voisine." },
      { q: "Médicaments ?", a: "Inuvair Nexthaler (asthme), stabilisé ; je rince bien la bouche." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Douleur ?",
        "Fièvre ?",
        "Fatigue ?",
        "Éruption cutanée ?",
        "Toux ?",
        "Demande depuis quand",
        "Actions entreprises ?",
        "Autres traitements ?",
        "Utilisation Inuvair : rince bien la bouche ?",
        "Asthme bien contrôlé ?",
      ]},
      { title: "Décision", items: [
        "Prise en charge symptomatique à l'officine",
      ]},
      { title: "Conseils", items: [
        "Hydratation",
        "Boissons chaudes",
        "Miel / citron / sucer des bonbons",
        "Paracétamol 1 g/prise, jusqu'à 3×/j (4-6 h entre les prises)",
        "Sédergine non recommandée",
        "Spray gorge : Néo-golaseptine ou Medica spray 3-5 pulv. 3×/j",
        "Ou comprimés gorge : Collutabs, Strepsils, Thymospray, Colludol",
      ]},
    ],
  },
  /* ===================== MYCOSE ONGLE PIED ===================== */
  {
    id: "ongle-1", plainte: "Mycose de l'ongle", variant: "Cas 1 — enceinte",
    opening: "Bonjour, j'ai une tache sur l'ongle, je voudrais qu'elle parte avant l'été. Je suis enceinte, mais j'aimerais connaître les possibilités de traitement pour en parler à mon gynécologue.",
    answers: [
      { q: "Quoi ?", a: "Une tache qui fait moins d'1/3 de la surface du gros orteil." },
      { q: "Étendue ?", a: "Un autre orteil semble un peu touché." },
      { q: "Localisation ?", a: "Uniquement la partie distale (pas d'atteinte de la matrice)." },
      { q: "Depuis ?", a: "Je l'ai remarqué il y a quelques semaines." },
      { q: "Actions ?", a: "Du vernis pour cacher, mais ça ne suffit pas." },
      { q: "Demande", a: "Je voudrais connaître les possibilités de traitement et comment ça se déroule." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Pose la question du quoi",
        "Tache sur l'ongle ?",
        "Couleur de la tache ?",
        "Partie distale atteinte (matrice non atteinte) ?",
        "Terme de la grossesse",
        "Actions entreprises ?",
        "Demande depuis quand",
        "Autres traitements ?",
      ]},
      { title: "Conseils", items: [
        "Ne pas partager les serviettes de bain",
        "Ne pas utiliser le même coupe-ongles",
        "Nettoyer et sécher entre les orteils",
        "Chaussettes en coton",
        "Ciclopirox : 1×/j, appliquer sur l'ongle (en débordant légèrement)",
        "Amorolfine : 1×/semaine, nettoyer et limer l'ongle",
        "Séchage : 30 s (ciclopirox) ou 3 min (amorolfine), attendre 6 h avant de nettoyer",
        "Effet : au moins 3 mois (repousse lente), traitement 9-12 mois (validité du flacon)",
        "La tache ne disparaîtra pas avec le produit",
        "Attendre la repousse de l'ongle pour la voir disparaître",
        "Ciclopirox : pas de vernis ; amorolfine : possible après séchage",
      ]},
    ],
  },
  {
    id: "ongle-2", plainte: "Mycose de l'ongle", variant: "Cas 2 — coureuse",
    opening: "Bonjour, j'ai une tache un peu jaune sur mon gros orteil. Pouvez-vous me délivrer un produit pour la faire disparaître ?",
    answers: [
      { q: "Depuis ?", a: "Apparue il y a quelques mois, elle a évolué." },
      { q: "Objectif ?", a: "Qu'elle soit partie avant l'été." },
      { q: "Sport ?", a: "Je fais beaucoup de course à pied (3×/semaine)." },
      { q: "Antécédents ?", a: "J'ai déjà utilisé le Daktarin spray pour des démangeaisons aux orteils." },
      { q: "Actions ?", a: "Rien, à part parfois du vernis pour cacher." },
      { q: "Pathologies ?", a: "Pas d'autres pathologies." },
      { q: "Localisation ?", a: "Partie distale, moins d'1/3 de la surface de l'ongle." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Pose la question du quoi",
        "Tache sur l'ongle ?",
        "Couleur de la tache ?",
        "Partie distale atteinte (matrice non atteinte) ?",
        "Actions entreprises ?",
        "Demande depuis quand",
        "Autres traitements ?",
      ]},
      { title: "Conseils", items: [
        "Ne pas partager les serviettes de bain",
        "Ne pas utiliser le même coupe-ongles",
        "Nettoyer et sécher entre les orteils",
        "Chaussettes en coton",
        "Ciclopirox : 1×/j, appliquer sur l'ongle (en débordant légèrement)",
        "Amorolfine : 1×/semaine, nettoyer et limer l'ongle",
        "Séchage : 30 s (ciclopirox) ou 3 min (amorolfine), attendre 6 h avant de nettoyer",
        "Effet : au moins 3 mois (repousse lente), traitement 9-12 mois (validité du flacon)",
        "La tache ne disparaîtra pas avec le produit",
        "Attendre la repousse de l'ongle pour la voir disparaître",
        "Ciclopirox : pas de vernis ; amorolfine : possible après séchage",
      ]},
    ],
  },
  /* ===================== MYCOSE VAGINALE ===================== */
  {
    id: "mycose-vag-1", plainte: "Mycose vaginale", variant: "Cas 1 — femme 32 ans",
    opening: "Bonjour, j'ai des irritations et des démangeaisons au niveau de mes parties intimes, auriez-vous quelque chose pour me soulager ? (femme de 32 ans)",
    answers: [
      { q: "Qui ?", a: "Femme de 32 ans, pas enceinte." },
      { q: "Saignements ?", a: "Pas de saignements irréguliers." },
      { q: "Pertes ?", a: "Pertes blanches sans odeur, léger prurit." },
      { q: "Autres ?", a: "Pas de fièvre, pas de douleurs, pas de nausées/vomissements." },
      { q: "Fréquence ?", a: "2e fois cette année (la dernière en vacances avec le maillot)." },
      { q: "Depuis ?", a: "Depuis 2-3 jours." },
      { q: "Actions ?", a: "Pas d'action entreprise." },
      { q: "Contraception ?", a: "Un anneau." },
      { q: "Préférence ?", a: "Je préfère un ovule pour le traitement." },
      { q: "Sécheresse ?", a: "Pas de sécheresse vaginale." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Demande pour qui",
        "Enceinte ?",
        "Immunodéprimée / diabétique ?",
        "Odeur ?",
        "Pertes (blanches, grumeleuses) ?",
        "Prurit ?",
        "Fièvre ?",
        "Douleurs lombaires / bas-ventre ?",
        "Saignements anormaux ?",
        "Demande depuis quand",
        "Fréquence ?",
        "Actions entreprises ?",
        "Autres médicaments (contraceptif : anneau ?)",
      ]},
      { title: "Conseils", items: [
        "Hygiène normale, pas excessive (eau tiède)",
        "Savon pH neutre",
        "Privilégier la douche (pas le bain)",
        "Bien sécher le périnée",
        "Sous-vêtements en coton",
        "Sous-vêtements pas trop serrés",
        "Changer quotidiennement de sous-vêtements",
        "Guérison spontanée possible sans traitement",
        "Canesten ovule, 1× le soir (prise unique)",
        "Rassurer : symptômes possibles 1-2 j après le traitement",
        "Si récidive > 4×/an : médecin",
        "Peut-être lié à l'anneau contraceptif",
        "Si persistance > 7 jours malgré traitement : médecin",
      ]},
    ],
  },
  {
    id: "mycose-vag-2", plainte: "Mycose vaginale", variant: "Cas 2 — femme 43 ans, diabète",
    opening: "Bonjour (femme de 43 ans), je viens chercher du Gyno-Daktarin. Mon partenaire peut-il l'utiliser également ?",
    answers: [
      { q: "Qui ?", a: "Femme de 43 ans." },
      { q: "Pathologies ?", a: "Diabète de type 2 depuis 2 ans." },
      { q: "Pertes ?", a: "Pertes blanches, sans odeur, avec sensation de brûlure et prurit." },
      { q: "Autres ?", a: "Pas de température, douleurs ou nausées." },
      { q: "Depuis ?", a: "Depuis 3 jours, 2e fois en 6 mois." },
      { q: "Actions ?", a: "Saforelle Fraîcheur et Progyn, sans résultat." },
      { q: "Médicaments ?", a: "Metformine 500 (3×/j), Coversyl 5, Cerazette." },
      { q: "Préférence ?", a: "Je préfère une crème." },
      { q: "Partenaire ?", a: "Je voudrais un produit pour traiter aussi mon partenaire." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Demande pour qui",
        "Enceinte ?",
        "Immunodéprimée / diabétique ?",
        "Odeur ?",
        "Pertes (blanches, grumeleuses) ?",
        "Prurit ?",
        "Fièvre ?",
        "Douleurs lombaires / bas-ventre ?",
        "Saignements anormaux ?",
        "Demande depuis quand",
        "Fréquence ?",
        "Actions entreprises ?",
        "Autres médicaments ?",
      ]},
      { title: "Conseils", items: [
        "Hygiène normale, pas excessive (eau tiède)",
        "Savon pH neutre",
        "Privilégier la douche (pas le bain)",
        "Bien sécher le périnée",
        "Sous-vêtements en coton",
        "Sous-vêtements pas trop serrés",
        "Changer quotidiennement de sous-vêtements",
        "Guérison spontanée possible sans traitement",
        "Canesten crème (Gyno-Daktarin RV), 1× le soir, 3 jours de suite",
        "Rassurer : symptômes possibles 1-2 j après le traitement",
        "Partenaire seulement si symptômes gênants : 2-3×/j, 1-2 semaines",
        "Si récidive > 4×/an : médecin",
        "Vérifier le contrôle glycémique : médecin",
        "Si persistance > 7 jours malgré traitement : médecin",
      ]},
    ],
  },
  /* ===================== SOMMEIL ===================== */
  {
    id: "sommeil-1", plainte: "Troubles du sommeil", variant: "Cas 1 — femme 35 ans",
    opening: "Je ne dors pas bien en ce moment, que pouvez-vous me proposer ? (femme de 35 ans)",
    answers: [
      { q: "Grossesse ?", a: "Pas enceinte." },
      { q: "Café ?", a: "5-6 cafés par jour." },
      { q: "Actions ?", a: "Pas d'action réellement entreprise." },
      { q: "Médicaments ?", a: "L-Thyroxine quotidiennement." },
      { q: "Impact ?", a: "Difficultés de concentration (impact modéré)." },
      { q: "MHD ?", a: "On ne m'a jamais proposé de mesures hygiéno-diététiques." },
      { q: "Alcool ?", a: "1 ou 2 verres le week-end entre amis." },
      { q: "Depuis ?", a: "Depuis 10 jours." },
      { q: "Fréquence ?", a: "Au moins 2 nuits/semaine, selon le stress du travail." },
      { q: "Sport ?", a: "Pas de sport." },
      { q: "Endormissement ?", a: "Parfois difficile." },
      { q: "Réveils ?", a: "Souvent vers 2-3 h, je pense au travail." },
      { q: "Pathologie ?", a: "Pas de pathologie sous-jacente." },
      { q: "Contexte ?", a: "Beaucoup de travail (clôture fiscale, je suis comptable)." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Pose la question du qui",
        "Réveil nocturne ?",
        "Difficulté d'endormissement ?",
        "Réveil précoce ?",
        "Baisse de vigilance en journée ?",
        "Combien de nuits par semaine ?",
        "Sport / sédentarité ?",
        "Stress ?",
        "Hygiène du sommeil ?",
        "Pathologie sous-jacente ?",
        "Demande depuis quand",
        "Actions entreprises ?",
        "Autres médicaments ?",
      ]},
      { title: "Conseils", items: [
        "Régularité des heures de lever/coucher",
        "S'exposer à la lumière naturelle",
        "Obscurité de la chambre",
        "Aérer la chambre",
        "Café avant 16 h",
        "Repas léger le soir",
        "Activité physique mais pas tardive",
        "Pas d'écran le soir",
        "Se préparer au sommeil 30 min avant (activité calme)",
        "Si pas d'endormissement après 20 min, changer de pièce",
        "S'assurer de l'équilibre de la L-Thyroxine (prise de sang ?)",
        "Passiflore (Sedistress 200) : 1-2 co 30 min avant le coucher",
        "Valériane (Sedistress Sleep) : 1 co avant (+ 1 co dans la soirée)",
        "Nustasium à court terme : 1 co 30 min avant le coucher",
      ]},
    ],
  },
  {
    id: "sommeil-2", plainte: "Troubles du sommeil", variant: "Cas 2 — homme 42 ans",
    opening: "Je suis crevé, je n'arrive plus à récupérer. Je me réveille presque toutes les nuits. Vous avez quelque chose pour ça ?",
    answers: [
      { q: "Qui ?", a: "Homme de 42 ans, chef de projet informatique." },
      { q: "Médicaments ?", a: "Pas de traitement quotidien." },
      { q: "Pathologie ?", a: "Aucune connue." },
      { q: "Café ?", a: "2 tasses le matin, 1 l'après-midi." },
      { q: "Alcool ?", a: "1 bière 2-3 soirs/semaine." },
      { q: "Actions ?", a: "Tisanes (verveine, camomille), peu d'effet." },
      { q: "Tabac ?", a: "Pas de stupéfiants ni de tabac." },
      { q: "Sport ?", a: "Pas de sport régulier (manque de temps)." },
      { q: "Depuis ?", a: "Depuis environ 3 semaines." },
      { q: "Fréquence ?", a: "4-5 nuits/semaine." },
      { q: "Impact ?", a: "Fatigue matinale, irritabilité, baisse de motivation." },
      { q: "Déclencheur ?", a: "Charge mentale, deadlines, surcharge de mails." },
      { q: "Endormissement ?", a: "45 min à 1 h, je ressasse les tâches du travail." },
      { q: "Réveils ?", a: "2 à 4 réveils/nuit, 20-40 min pour me rendormir, réveil trop matinal." },
      { q: "Sécurité ?", a: "Pas de ronflements importants ni de pauses respiratoires." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Pose la question du qui",
        "Réveil nocturne ?",
        "Difficulté d'endormissement ?",
        "Réveil précoce ?",
        "Baisse de vigilance en journée ?",
        "Combien de nuits par semaine ?",
        "Sport / sédentarité ?",
        "Stress ?",
        "Hygiène du sommeil ?",
        "Pathologie sous-jacente ?",
        "Demande depuis quand",
        "Actions entreprises ?",
        "Autres médicaments ?",
      ]},
      { title: "Conseils", items: [
        "Régularité des heures de lever/coucher",
        "S'exposer à la lumière naturelle",
        "Obscurité de la chambre",
        "Aérer la chambre",
        "Café avant 16 h",
        "Repas léger le soir",
        "Activité physique mais pas tardive",
        "Pas d'écran le soir",
        "Se préparer au sommeil 30 min avant (activité calme)",
        "Si pas d'endormissement après 20 min, changer de pièce",
        "Passiflore (Sedistress 200) : 1-2 co 30 min avant le coucher",
        "Valériane (Sedistress Sleep) : 1 co avant (+ 1 co dans la soirée)",
        "Nustasium à court terme : 1 co 30 min avant le coucher",
        "Consultation recommandée si persistance",
      ]},
    ],
  },
  /* ===================== CYSTITE ===================== */
  {
    id: "cystite-1", plainte: "Cystite", variant: "Cas 1 — femme 24 ans",
    opening: "Jeune femme de 24 ans, samedi 12h58. Elle pense avoir une infection urinaire et veut quelque chose pour la soulager immédiatement.",
    answers: [
      { q: "Grossesse ?", a: "Non." },
      { q: "Symptômes ?", a: "Ça démange un peu, juste une gêne à la miction." },
      { q: "Alarme ?", a: "Pas de fièvre, pas de douleur dans le bas du dos, pas de nausées." },
      { q: "Depuis ?", a: "Depuis la veille au soir, quasi jamais de cystite." },
      { q: "Médicaments ?", a: "Contraception orale." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Femme — facteurs de risque ?",
        "Enceinte ?",
        "Fièvre ?",
        "Sang dans les urines ?",
        "Douleur bas du dos / bas-ventre ?",
        "Nausées / vomissements ?",
        "Description des symptômes ?",
        "Demande depuis quand (< 2-3 jours)",
        "Actions entreprises ?",
        "Autres médicaments (contraception orale) ?",
      ]},
      { title: "Décision", items: [
        "Aucun signe d'alerte : prise en charge à l'officine",
      ]},
      { title: "Conseils", items: [
        "Douleur : paracétamol",
        "Guérison spontanée possible",
        "Traitement : busserole, 2 co 3×/j, max 7 jours",
        "Attention : colore les urines brun-vert",
        "Si pas d'amélioration en 2-3 j : médecin",
        "Si aggravation des symptômes : médecin",
        "Hydratation 1,5 L/j",
        "S'essuyer d'avant en arrière aux WC",
        "Savon doux pH neutre",
        "Hygiène normale, pas excessive",
        "Ne pas se retenir d'uriner",
        "Éviter les vêtements trop serrés (privilégier le coton)",
      ]},
    ],
  },
  {
    id: "cystite-2", plainte: "Cystite", variant: "Cas 2 — femme 54 ans, diabète",
    opening: "Femme de 54 ans, garde du dimanche 17h. Elle voudrait quelque chose pour apaiser un inconfort urinaire.",
    answers: [
      { q: "Symptômes ?", a: "Besoin impérieux d'uriner et brûlure en fin de miction ; je pense tenir jusqu'à demain." },
      { q: "Récurrence ?", a: "J'ai souvent ça depuis quelque temps, j'ai l'habitude." },
      { q: "Alarme ?", a: "Pas de fièvre, pas de douleur dans le bas du dos, pas de nausées, pas de sang." },
      { q: "Grossesse ?", a: "Non." },
      { q: "Diabète ?", a: "Oui (déduit des médicaments pris)." },
      { q: "Depuis ?", a: "Depuis ce matin." },
      { q: "Actions ?", a: "Beaucoup d'eau et du jus de cranberry, sans amélioration." },
      { q: "Médicaments ?", a: "Jardiance 25, Metformine 850, Bisoprolol 5, Atorvastatine 20, Mirena, Oestrogel, Monuril, Uricran Comfort, D-mannose." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Femme — à confirmer",
        "Facteur de risque : diabète (DPP / médicaments)",
        "Description des symptômes ?",
        "Sang dans les urines ?",
        "Fièvre / frissons ?",
        "Douleur bas du dos / bas-ventre ?",
        "Nausées / vomissements ?",
        "Demande depuis quand (< 2-3 jours)",
        "Actions entreprises (jus de cranberry) ?",
        "Autres médicaments (eID / Jardiance…) ?",
      ]},
      { title: "Décision", items: [
        "Signe d'alerte : diabète (prudence)",
        "Patiente peut tenir jusqu'à demain → OK officine avec conseils",
      ]},
      { title: "Conseils", items: [
        "Conseiller de parler du Jardiance (cause possible) au médecin",
        "Douleur (immédiat) : paracétamol",
        "Guérison spontanée possible en 48 h chez 25% des femmes",
        "Traitement possible : busserole, 2 co 3×/j, max 7 jours",
        "Attention : colore les urines brun-vert",
        "Si pas d'amélioration en 2-3 j : médecin",
        "Si aggravation des symptômes : médecin",
        "Hydratation 1,5 L/j",
        "S'essuyer d'avant en arrière aux WC",
        "Savon doux pH neutre",
        "Hygiène normale, pas excessive",
        "Ne pas se retenir d'uriner",
        "Éviter les vêtements trop serrés (privilégier le coton)",
      ]},
    ],
  },
  /* ===================== TOUX ===================== */
  {
    id: "toux-1", plainte: "Toux", variant: "Cas 1 — enfant 18 mois",
    opening: "Bonjour, je souhaite un sirop pour la toux de mon enfant de 18 mois. Le Muco Rhinathiol enfant convient-il ? J'en ai encore à la maison.",
    answers: [
      { q: "Qui ?", a: "Enfant de 18 mois, très bon état général, enrhumé, beaucoup de glaires mais claires." },
      { q: "Depuis ?", a: "Depuis 3 jours." },
      { q: "Nez ?", a: "Le nez coule beaucoup, plusieurs rinçages au sérum physiologique par jour." },
      { q: "Respiration ?", a: "Dort normalement, pas de respiration sifflante, ne tousse pas plus la nuit." },
      { q: "Toux ?", a: "Pas de toux qui fait vomir, pas de toux en quinte." },
      { q: "Fièvre ?", a: "Un peu fiévreux (37-37,5 °C), ça baisse avec le paracétamol." },
      { q: "Antécédents ?", a: "Plusieurs bronchiolites étant petit, mais plus depuis longtemps." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Demande qui est le patient (enfant de 18 mois)",
        "Fièvre ?",
        "Rhume ?",
        "Respiration sifflante ?",
        "Toux qui fait vomir ?",
        "Toux en quinte ?",
        "Toux nocturne ?",
        "Expectorations claires ?",
        "Demande depuis quand",
        "Actions entreprises (Muco Rhinathiol à la maison) ?",
        "Autres médicaments ?",
      ]},
      { title: "Décision", items: [
        "Muco Rhinathiol non recommandé (CI < 2 ans)",
        "Aucun sirop statut médicament indiqué < 2 ans",
      ]},
      { title: "Conseils", items: [
        "Hydratation",
        "Aérer",
        "Éviter les irritants (poussière, tabac)",
        "Humidifier l'air",
        "Nettoyer le nez au sérum physiologique",
        "Miel OK (> 1 an)",
        "Paracétamol si fièvre",
        "Médecin si aggravation des symptômes",
        "Médecin si pas d'amélioration en 7 jours",
        "Médecin si fièvre pendant 3 jours",
      ]},
    ],
  },
  {
    id: "toux-2", plainte: "Toux", variant: "Cas 2 — homme 65 ans",
    opening: "Bonjour, je voudrais un sirop pour ma toux.",
    answers: [
      { q: "Qui ?", a: "Homme de 65 ans." },
      { q: "Pathologies ?", a: "Diabète et hypertension." },
      { q: "Médicaments ?", a: "Metformine 500 (3×/j, 1 an), Bipressil 5/5 (3 ans)." },
      { q: "Symptômes ?", a: "Toux grasse (peu colorée) depuis 5 jours, avec nez qui coule." },
      { q: "Fièvre ?", a: "Pas de fièvre." },
      { q: "Nuit ?", a: "Je me réveille la nuit à cause de la toux." },
      { q: "Actions ?", a: "Un sirop restant à la maison, je crois que ça s'appelle Broncho…, il est vert." },
    ],
    sections: [
      { title: "Interrogatoire", items: [
        "Demande qui est le patient (homme, 65 ans)",
        "Diabète + hypertension",
        "Fièvre ?",
        "Rhume ?",
        "Respiration sifflante ?",
        "Toux qui fait vomir ?",
        "Toux en quinte ?",
        "Toux nocturne ?",
        "Expectorations claires ?",
        "Demande depuis quand",
        "Actions entreprises (sirop dextrométhorphane) ?",
        "Autres médicaments (metformine + bisoprolol/périndopril) ?",
      ]},
      { title: "Décision", items: [
        "Dextrométhorphane non recommandé pour une toux grasse (éventuellement la nuit)",
        "OK sirop toux grasse à base de guaïfénésine (ou acétylcystéine)",
      ]},
      { title: "Conseils", items: [
        "Éviter de donner tard le soir (pour ne pas tousser la nuit)",
        "Éviter le sucre dans le sirop",
        "Hydratation",
        "Aérer",
        "Éviter les irritants (poussière, tabac)",
        "Humidifier l'air",
        "Nettoyer le nez au sérum physiologique",
        "Tisane au thym",
        "Miel (attention : diabète !)",
        "Paracétamol si fièvre",
        "Médecin si fièvre > 38 °C pendant 3 jours",
        "Médecin si pas d'amélioration en 7 jours",
        "Une toux peut durer jusqu'à 3 semaines",
        "Médecin si aggravation de la toux",
      ]},
    ],
  },
  /* ===================== CONTRACEPTION D'URGENCE (grille seule) ===================== */
  {
    id: "contraception-urgence", plainte: "Contraception d'urgence", variant: "Station grille",
    opening: "Bonjour, j'aurais besoin d'une contraception d'urgence.",
    answers: [],
    sections: [
      { title: "Interrogatoire", items: [
        "Pour qui ?",
        "Contraception continue ? Si oui, laquelle ?",
        "Échec de la contraception continue ?",
        "3e semaine de plaquette (patch / anneau) précédente ?",
        "RSNP ? Si oui, quand ?",
        "Autre RSNP depuis les dernières règles ?",
        "Médicaments pris régulièrement ?",
        "Tisanes / compléments alimentaires ?",
        "Autre CU (UPA – LNG) dans les 7 jours précédents ?",
        "Allaitement ?",
        "Poids > 70 kg ?",
      ]},
      { title: "Informations", items: [
        "Alternatives et choix pour la patiente",
        "BUM CU",
        "Efficacité : pas 100 %",
        "Effets indésirables (troubles digestifs, retard de règles)",
        "Modalités de prise : nombre de comprimés ; que faire si vomissements",
        "Prendre avec un verre d'eau",
        "Sécurisation du cycle : la CU n'est pas un moyen contraceptif",
        "Test de grossesse",
        "Fiche CU distribuée / commentée",
        "Fiche IST",
      ]},
      { title: "Attitude & communication", items: [
        "Valorisation de la démarche",
        "Justification du questionnement (ex : poids)",
        "Consignes précises",
        "Langage « patient » — pas de jargon",
        "Clôture : résumé — besoin d'autres informations ?",
      ]},
    ],
  },
];

/* ---------- Pièges / erreurs fréquentes par cas (extraits du PDF) ---------- */
const PITFALLS = {
  "brulure-bebe": ["Conseille de mettre de la glace", "Délivre la crème sans interrogatoire", "Rend le pansement obligatoire", "Oublie de questionner la maltraitance"],
  "brulure-adulte": ["Délivre la Flammazine (sans intérêt, < hydrogel)", "Conseille de percer les cloques", "Conseille de mettre de la glace", "Oublie le statut vaccinal tétanos", "Néglige le risque lié au diabète"],
  "hemorroides-1": ["Propose une crème aux corticoïdes malgré le sang", "Ne réfère pas vers le médecin (> 50 ans)", "Ne propose pas de colotest", "Délivre sans interroger sur le sang / les selles"],
  "hemorroides-2": ["Autorise l'ibuprofène (enceinte)", "Donne un corticoïde plus de 1-2 semaines", "Néglige la lutte contre la constipation"],
  "yeux-secs-1": ["Délivre un collyre antibiotique / désinfectant", "Oublie les mesures hygiéno-diététiques (écrans, 20-20-20)", "Ne questionne pas le travail sur écran"],
  "yeux-secs-2": ["Conseille un collyre avec conservateurs (port de lentilles)", "Conseille d'arrêter la pilule (CI Roaccutane)", "Ignore le Roaccutane"],
  "rhinite-1": ["Délivre sans questionner les signaux d'alarme", "Oublie les conseils non pharmacologiques"],
  "rhinite-2": ["Ne vérifie pas le contrôle de l'asthme", "Promet un effet immédiat du mométasone (min 4 jours)"],
  "gorge-1": ["Délivre un AINS / le Strepfen (enceinte)", "Ne réfère pas (risque CMV)", "Propose Collutabs / Strepsils / Thymospray / Colludol (enceinte)"],
  "gorge-2": ["Recommande la Sédergine (aspirine)", "Ne vérifie pas le contrôle de l'asthme"],
  "ongle-1": ["Promet la disparition de la tache avec le produit", "Sous-estime la durée du traitement (9-12 mois)"],
  "ongle-2": ["Promet une disparition rapide avant l'été", "Oublie les conseils d'hygiène (pieds, chaussettes)"],
  "mycose-vag-1": ["Délivre une crème corticoïde", "Oublie d'évoquer l'anneau comme cause", "Délivre sans questionner la grossesse"],
  "mycose-vag-2": ["Traite le partenaire systématiquement", "Néglige le contrôle glycémique (diabète)", "Délivre sans questionner le diabète"],
  "sommeil-1": ["Propose d'emblée un hypnotique sans mesures hygiéno-diététiques", "Néglige l'équilibre de la L-Thyroxine"],
  "sommeil-2": ["Propose un médicament sans aborder l'hygiène du sommeil", "Ne propose pas de consultation si besoin"],
  "cystite-1": ["Délivre un antibiotique sans ordonnance", "Délivre sans écarter les signes d'alerte"],
  "cystite-2": ["Prend en charge sans prudence malgré le diabète", "N'évoque pas le Jardiance comme cause possible", "Ne propose pas d'orienter vers le médecin"],
  "toux-1": ["Délivre le Muco Rhinathiol / un sirop (CI < 2 ans)", "Délivre un antitussif", "Oublie le rinçage de nez au sérum physiologique"],
  "toux-2": ["Donne un sirop au dextrométhorphane (toux grasse)", "Donne du miel sans prévenir (diabète)", "Conseille le sirop tard le soir"],
  "contraception-urgence": ["Délivre sans interroger (poids, délai, autre CU)", "Présente la CU comme un moyen contraceptif régulier", "Oublie la fiche IST / le test de grossesse"],
};

/* ---------- Stockage admin (cas ajoutés / modifiés / masqués) ---------- */
const ADMIN_STORE_KEY = 'osce_admin_cases_v1';
function loadAdminStore() {
  try { const r = localStorage.getItem(ADMIN_STORE_KEY); const s = r ? JSON.parse(r) : null; return (s && s.overrides) ? { overrides: s.overrides, hidden: s.hidden || [] } : { overrides: {}, hidden: [] }; }
  catch (e) { return { overrides: {}, hidden: [] }; }
}
function saveAdminStore(store) { try { localStorage.setItem(ADMIN_STORE_KEY, JSON.stringify(store)); } catch (e) {} if (window.cloudPushAdmin) cloudPushAdmin(store); }
function isBaseCase(id) { return CASES.some(c => c.id === id); }

/* Liste effective : cas de base (éventuellement remplacés/masqués) + cas personnalisés. */
function effectiveCases() {
  const store = loadAdminStore();
  const baseIds = new Set(CASES.map(c => c.id));
  const list = [];
  CASES.forEach(c => { if (store.hidden.includes(c.id)) return; list.push(store.overrides[c.id] || c); });
  Object.keys(store.overrides).forEach(id => {
    if (!baseIds.has(id) && !store.hidden.includes(id)) list.push(store.overrides[id]);
  });
  return list;
}

/* Regroupe les cas par plainte, dans l'ordre d'apparition. */
function casesByPlainte() {
  const groups = [];
  const index = {};
  effectiveCases().forEach(c => {
    if (!(c.plainte in index)) { index[c.plainte] = groups.length; groups.push({ plainte: c.plainte, cases: [] }); }
    groups[index[c.plainte]].cases.push(c);
  });
  return groups;
}
function getCase(id) {
  const c = effectiveCases().find(c => c.id === id);
  if (!c) return null;
  return c.pitfalls ? c : Object.assign({}, c, { pitfalls: PITFALLS[id] || [] });
}
